-- Top IITs
INSERT INTO college (id, college_name, college_email, city, state, country, website)
VALUES (1, 'Indian Institute of Technology Delhi', 'admin@iitd.ac.in', 'New Delhi', 'Delhi', 'India',
        'https://www.iitd.ac.in'),
       (2, 'Indian Institute of Technology Bombay', 'admin@iitb.ac.in', 'Mumbai', 'Maharashtra', 'India',
        'https://www.iitb.ac.in'),
       (3, 'Indian Institute of Technology Madras', 'admin@iitm.ac.in', 'Chennai', 'Tamil Nadu', 'India',
        'https://www.iitm.ac.in'),
       (4, 'Indian Institute of Technology Kanpur', 'admin@iitk.ac.in', 'Kanpur', 'Uttar Pradesh', 'India',
        'https://www.iitk.ac.in'),
       (5, 'Indian Institute of Technology Kharagpur', 'admin@iitkgp.ac.in', 'Kharagpur', 'West Bengal', 'India',
        'https://www.iitkgp.ac.in'),
       (6, 'Indian Institute of Technology Roorkee', 'admin@iitr.ac.in', 'Roorkee', 'Uttarakhand', 'India',
        'https://www.iitr.ac.in'),
       (7, 'Indian Institute of Technology Guwahati', 'admin@iitg.ac.in', 'Guwahati', 'Assam', 'India',
        'https://www.iitg.ac.in'),
       (8, 'Indian Institute of Technology Hyderabad', 'admin@iith.ac.in', 'Hyderabad', 'Telangana', 'India',
        'https://www.iith.ac.in'),

-- Top NITs
       (9, 'National Institute of Technology Trichy', 'admin@nitt.edu', 'Tiruchirappalli', 'Tamil Nadu', 'India',
        'https://www.nitt.edu'),
       (10, 'National Institute of Technology Karnataka', 'admin@nitk.ac.in', 'Surathkal', 'Karnataka', 'India',
        'https://www.nitk.ac.in'),
       (11, 'National Institute of Technology Warangal', 'admin@nitw.ac.in', 'Warangal', 'Telangana', 'India',
        'https://www.nitw.ac.in'),
       (12, 'National Institute of Technology Rourkela', 'admin@nitrkl.ac.in', 'Rourkela', 'Odisha', 'India',
        'https://www.nitrkl.ac.in'),
       (13, 'National Institute of Technology Calicut', 'admin@nitc.ac.in', 'Calicut', 'Kerala', 'India',
        'https://www.nitc.ac.in'),

-- BITS & Private Universities
       (14, 'BITS Pilani', 'admin@pilani.bits-pilani.ac.in', 'Pilani', 'Rajasthan', 'India',
        'https://www.bits-pilani.ac.in'),
       (15, 'BITS Pilani Goa Campus', 'admin@goa.bits-pilani.ac.in', 'Zuarinagar', 'Goa', 'India',
        'https://www.bits-goa.ac.in'),
       (16, 'BITS Pilani Hyderabad Campus', 'admin@hyderabad.bits-pilani.ac.in', 'Hyderabad', 'Telangana', 'India',
        'https://www.bits-hyderabad.ac.in'),
       (17, 'VIT Vellore', 'admin@vit.ac.in', 'Vellore', 'Tamil Nadu', 'India', 'https://vit.ac.in'),
       (18, 'SRM Institute of Science and Technology', 'admin@srmist.edu.in', 'Chennai', 'Tamil Nadu', 'India',
        'https://www.srmist.edu.in'),
       (19, 'Manipal Institute of Technology', 'admin@manipal.edu', 'Manipal', 'Karnataka', 'India',
        'https://manipal.edu'),
       (20, 'Thapar Institute of Engineering and Technology', 'admin@thapar.edu', 'Patiala', 'Punjab', 'India',
        'https://www.thapar.edu'),

-- Universities & Others
       (21, 'Delhi Technological University', 'admin@dtu.ac.in', 'Delhi', 'Delhi', 'India', 'https://www.dtu.ac.in'),
       (22, 'Netaji Subhas University of Technology', 'admin@nsut.ac.in', 'Delhi', 'Delhi', 'India',
        'https://www.nsut.ac.in'),
       (23, 'Anna University', 'admin@annauniv.edu', 'Chennai', 'Tamil Nadu', 'India', 'https://www.annauniv.edu'),
       (24, 'Jadavpur University', 'admin@jadavpuruniversity.in', 'Kolkata', 'West Bengal', 'India',
        'http://www.jaduniv.edu.in'),
       (25, 'Banaras Hindu University', 'admin@bhu.ac.in', 'Varanasi', 'Uttar Pradesh', 'India',
        'https://www.bhu.ac.in'),
       (26, 'Amity University', 'admin@amity.edu', 'Noida', 'Uttar Pradesh', 'India', 'https://www.amity.edu'),
       (27, 'Chandigarh University', 'admin@cumail.in', 'Mohali', 'Punjab', 'India', 'https://www.cuchd.in'),
       (28, 'LPU Phagwara', 'admin@lpu.co.in', 'Phagwara', 'Punjab', 'India', 'https://www.lpu.in'),
       (29, 'Symbiosis International University', 'admin@siu.edu.in', 'Pune', 'Maharashtra', 'India',
        'https://siu.edu.in'),
       (30, 'Christ University', 'admin@christuniversity.in', 'Bengaluru', 'Karnataka', 'India',
        'https://christuniversity.in'),

-- Adding more to reach 50...
       (31, 'IIT Indore', 'admin@iiti.ac.in', 'Indore', 'Madhya Pradesh', 'India', 'https://www.iiti.ac.in'),
       (32, 'IIT Gandhinagar', 'admin@iitgn.ac.in', 'Gandhinagar', 'Gujarat', 'India', 'https://www.iitgn.ac.in'),
       (33, 'IIT Ropar', 'admin@iitrpr.ac.in', 'Ropar', 'Punjab', 'India', 'https://www.iitrpr.ac.in'),
       (34, 'IIT Patna', 'admin@iitp.ac.in', 'Patna', 'Bihar', 'India', 'https://www.iitp.ac.in'),
       (35, 'IIT Bhubaneswar', 'admin@iitbbs.ac.in', 'Bhubaneswar', 'Odisha', 'India', 'https://www.iitbbs.ac.in'),
       (36, 'IIT Jodhpur', 'admin@iitj.ac.in', 'Jodhpur', 'Rajasthan', 'India', 'https://www.iitj.ac.in'),
       (37, 'IIT Mandi', 'admin@iitmandi.ac.in', 'Mandi', 'Himachal Pradesh', 'India', 'https://www.iitmandi.ac.in'),
       (38, 'NIT Allahabad', 'admin@mnnit.ac.in', 'Prayagraj', 'Uttar Pradesh', 'India', 'http://www.mnnit.ac.in'),
       (39, 'NIT Jaipur', 'admin@mnit.ac.in', 'Jaipur', 'Rajasthan', 'India', 'http://www.mnit.ac.in'),
       (40, 'NIT Nagpur', 'admin@vnit.ac.in', 'Nagpur', 'Maharashtra', 'India', 'http://vnit.ac.in'),
       (41, 'NIT Kurukshetra', 'admin@nitkkr.ac.in', 'Kurukshetra', 'Haryana', 'India', 'http://www.nitkkr.ac.in'),
       (42, 'NIT Silchar', 'admin@nits.ac.in', 'Silchar', 'Assam', 'India', 'http://www.nits.ac.in'),
       (43, 'NIT Durgapur', 'admin@nitdgp.ac.in', 'Durgapur', 'West Bengal', 'India', 'http://www.nitdgp.ac.in'),
       (44, 'NIT Jalandhar', 'admin@nitj.ac.in', 'Jalandhar', 'Punjab', 'India', 'http://www.nitj.ac.in'),
       (45, 'NIT Meghalaya', 'admin@nitm.ac.in', 'Shillong', 'Meghalaya', 'India', 'http://www.nitm.ac.in'),
       (46, 'IIIT Hyderabad', 'admin@iiit.ac.in', 'Hyderabad', 'Telangana', 'India', 'https://www.iiit.ac.in'),
       (47, 'IIIT Bangalore', 'admin@iiitb.ac.in', 'Bengaluru', 'Karnataka', 'India', 'https://www.iiitb.ac.in'),
       (48, 'IIIT Delhi', 'admin@iiitd.ac.in', 'New Delhi', 'Delhi', 'India', 'https://www.iiitd.ac.in'),
       (49, 'IIIT Allahabad', 'admin@iiita.ac.in', 'Prayagraj', 'Uttar Pradesh', 'India', 'https://www.iiita.ac.in'),
       (50, 'IIIT Gwalior', 'admin@iiitm.ac.in', 'Gwalior', 'Madhya Pradesh', 'India',
        'https://www.iiitm.ac.in'),
       (51, 'Amity University Online', 'admin@amityonline.com', 'Noida', 'Uttar Pradesh', 'India',
        'https://amityonline.com'),
       (52, 'AKI Poona College of Arts, Science & Commerce', 'admin@poonacollege.edu.in', 'Pune', 'Maharashtra',
        'India', 'https://poonacollege.edu.in'),
       (53, 'Savitribai Phule Pune University', 'admin@unipune.ac.in', 'Pune', 'Maharashtra', 'India',
        'http://www.unipune.ac.in'),
       (54, 'Fergusson College (DES)', 'admin@fergusson.edu', 'Pune', 'Maharashtra', 'India',
        'https://www.fergusson.edu'),
       (55, 'Brihan Maharashtra College of Commerce (BMCC)', 'admin@bmcc.ac.in', 'Pune', 'Maharashtra', 'India',
        'https://www.bmcc.ac.in'),
       (56, 'COEP Technological University', 'admin@coep.org.in', 'Pune', 'Maharashtra', 'India',
        'https://www.coep.org.in'),
       (57, 'Symbiosis Institute of Tech (SIT Pune)', 'admin@sitpune.edu.in', 'Pune', 'Maharashtra', 'India',
        'https://www.sitpune.edu.in'),
-- Additional Major Hubs
       (58, 'University of Mumbai', 'admin@mu.ac.in', 'Mumbai', 'Maharashtra', 'India', 'https://mu.ac.in'),
       (59, 'Loyola College', 'admin@loyolacollege.edu', 'Chennai', 'Tamil Nadu', 'India',
        'https://www.loyolacollege.edu'),
       (60, 'St. Stephens College', 'admin@ststephens.edu', 'Delhi', 'Delhi', 'India',
        'https://www.ststephens.edu') ON CONFLICT (id) DO NOTHING;